version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./:/app/
            # trailing slash is essential in order to use "node_modules" volume instead of
            # "node_modules" from our host
            - nextjs_node_modules:/app/node_modules/
            - /app/.next
        environment:
            - NODE_ENV=development

volumes:
    nextjs_node_modules:
